[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


[[patches]]
[patches.pattern]
target = """=[SMODS _ "src/utils.lua"]"""
pattern = '''if ret.override_scalar_value and not args.block_overrides.scalar then scalar_value = ret.override_scalar_value.value; SMODS.calculate_effect(ret.override_scalar_value, _card) end'''
position = "after"
payload = '''
if ret.override_operation and not args.block_overrides.operation then args.operation = ret.override_operation.value; SMODS.calculate_effect(ret.override_operation, _card) end
'''
match_indent = true